name:                haricot
version:             0.1.0.0
github:              sboehler/haricot
license:             BSD3
author:              Silvio Böhler
maintainer:          sboehler@gmail.com
copyright:           2017 Silvio Böhler

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A Haskell parser for beancount
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/haricot#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- exceptions
- filepath
- megaparsec
- mtl
- optparse-applicative
- prettyprinter
- scientific
- text
- time

default-extensions:
- DuplicateRecordFields
- NamedFieldPuns
- OverloadedStrings
- RecordWildCards
- DeriveFunctor
- LambdaCase
- FlexibleContexts
- TypeFamilies
- TupleSections
- ScopedTypeVariables
- FlexibleInstances

ghc-options:
  - -Wall

executables:
  haricot:
    main: Main.hs
    source-dirs:
      - app
      - src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
