name:                haricot
version:             0.1.0.0
github:              sboehler/haricot
license:             BSD3
author:              Silvio Böhler
maintainer:          sboehler@gmail.com
copyright:           2017 Silvio Böhler

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A Haskell parser for beancount
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/haricot#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- Decimal
- filepath
- free
- lens
- parsec
- parsec3-numbers
- mtl
- prettyprinter
- exceptions
- text
- time

default-extensions:
- DataKinds
- DeriveGeneric
- DeriveFunctor
- GeneralizedNewtypeDeriving
- DuplicateRecordFields
- NamedFieldPuns
- LambdaCase
- FlexibleContexts
- OverloadedStrings
- FlexibleInstances
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- UndecidableInstances
- TypeFamilies
- TypeOperators

ghc-options:
  - -Wall

library:
  source-dirs: src

executables:
  haricot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haricot


tests:
  haricot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haricot
