name:                beans
version:             0.0.2.0
github:              sboehler/beans
license:             BSD3
author:              Silvio Böhler
maintainer:          sboehler@gmail.com
copyright:           2017 Silvio Böhler

extra-source-files:
- README.org
- ChangeLog.md

synopsis:            A plain text accounting tool
category:            Finance

description:         Please see the README on Github at <https://github.com/sboehler/beans#readme>

default-extensions:
- DuplicateRecordFields
- NamedFieldPuns
- OverloadedStrings
- RecordWildCards
- ParallelListComp
- DeriveFunctor
- ApplicativeDo
- LambdaCase
- FlexibleContexts
- TypeFamilies
- StandaloneDeriving
- MultiParamTypeClasses
- FunctionalDependencies
- TemplateHaskell
- TupleSections
- ScopedTypeVariables
- FlexibleInstances

ghc-options:
  - -Wall
  - -j
  - -fwarn-incomplete-record-updates

dependencies:
  - base >= 4.7 && < 5
  - bifunctors
  - bytestring
  - containers
  - Decimal
  - exceptions
  - filepath
  - groups
  - lens
  - megaparsec == 7.*
  - mtl
  - optparse-applicative
  - parser-combinators
  - prettyprinter
  - regex-pcre
  - scientific
  - text
  - time
  - tasty
  - tasty-smallcheck
  - tasty-quickcheck
  - tasty-hunit
  - tasty-golden
  - text

executables:
  beans:
    main: Main.hs
    source-dirs:
      - app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - beans

library:
  source-dirs:
    - src

tests:
  test:
    main: test.hs
    source-dirs:
      - tests
    dependencies:
      - beans
