name: beans-web
version: '0.1.0.0'
description: An experimental web-based accounting engine
category: Web
author: Silvio Böhler
maintainer: sboehler@noreply.users.github.com
copyright: 2019 Silvio Böhler
license: BSD3
github: sboehler/web-app
extra-source-files:
- README.md
ghc-options:
  - -Wall
  - -j
  - -fwarn-incomplete-record-updates
library:
  source-dirs: src
  default-extensions:
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DerivingVia
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - ImpredicativeTypes
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MonadFailDesugaring
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TypeApplications
  - TypeSynonymInstances
  - TupleSections
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances
  - UndecidableInstances
  - ViewPatterns
  exposed-modules:
  - App
  dependencies:
  - aeson
  - base >=4.7 && <5
  - beam-core
  - beam-migrate
  - beam-sqlite
  - bytestring
  - cereal
  - containers
  - microlens-platform
  - optparse-applicative
  - sqlite-simple
  - resource-pool
  - rio
  - rio-orphans
  - servant
  - servant-server
  - text
  - transformers
  - time
  - wai
  - warp
executables:
  beans-web-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - base
    - beans-web
